### ISSUE TITLE
nextjs 12.3.0 - Error: Cannot find module 'colors'

### ISSUE THREAD

**Issue by jalmendhry** [micheleriva/krabs#40]
Followed installation correctly, using the latest version of next js.

Receiving the error 

`code: 'MODULE_NOT_FOUND'`

`node_modules/krabs/dist/utils/env/index.js`
`node_modules/krabs/dist/utils/tenants/findTenant.js',`
`node_modules/krabs/dist/express-krabs/index.js',`
`index.js'`

Works with the example version of 9.5.5

Edit: I pulled another copy of the example and it works the first time. Not sure what the problem is now...

Edit 2: I had to run `npm install colors ` to solve this...

**Comment by x0y-gt** [comment]
Having the same issue, thanks for the hint @jalmendhry
